version: '3'
services:
  postgres:
#    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nakama
    expose:
      - "8080"
      - "5432"
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nakama"]  # Проверка доступности базы данных
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nakama:
    build: .
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres://postgres:postgres@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres://postgres:postgres@postgres:5432/nakama
    volumes:
      - ${JSON_FILES_PATH}:/path/inside/container
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  data:
